
(function(w){
  function cloneRules(source){return (source||[]).map(function(r){return {id:r.id||'',name:r.name||'',enabled:!!r.enabled,priority:Number(r.priority)||100,scope:r.scope||'图层名',matchMode:r.matchMode||'通配符',pattern:r.pattern||'',excludePattern:r.excludePattern||'',parentGroup:r.parentGroup||'',parentClass:r.parentClass||'',tagText:r.tagText||'',mergeMode:r.mergeMode||'覆盖空值',applicableObjectTypes:r.applicableObjectTypes||'',source:r.source||'用户规则',confidenceBase:Number(r.confidenceBase)||.78,stopAfterMatch:!!r.stopAfterMatch};});}
  function b64(value){return btoa(unescape(encodeURIComponent(value||'')));}
  function RecognitionRulesPage(options){this.options=options||{};this.root=document.getElementById(this.options.rootId||'recognitionRulesPage');if(!this.root)throw new Error('未找到属性识别表页面根节点。');this.rules=cloneRules(this.options.data);this.defaultRules=cloneRules(this.options.defaultData);this.selectedIndex=this.rules.length?0:-1;this.matchModes=['精确','包含','通配符','关键词组合','模板','正则'];this.mergeModes=['覆盖空值','覆盖','首条命中'];this.bound=false;this.savedPayload=this.buildPayload();}
  RecognitionRulesPage.prototype.$=function(selector){return this.root.querySelector(selector);};
  RecognitionRulesPage.prototype.post=function(name,arg){if(typeof this.options.post==='function')this.options.post(name,arg||'');};
  RecognitionRulesPage.prototype.toast=function(message,kind){if(typeof this.options.toast==='function')this.options.toast(message,kind||'info');};
  RecognitionRulesPage.prototype.ruleText=function(rule){return ((rule.name||'')+' '+(rule.scope||'')+' '+(rule.matchMode||'')+' '+(rule.pattern||'')+' '+(rule.excludePattern||'')+' '+(rule.parentGroup||'')+' '+(rule.parentClass||'')+' '+(rule.tagText||'')).toLowerCase();};
  RecognitionRulesPage.prototype.cell=function(row,text){var cell=document.createElement('td');if(text!==undefined)cell.textContent=text;row.appendChild(cell);return cell;};
  RecognitionRulesPage.prototype.textInput=function(value,oninput){var input=document.createElement('input');input.type='text';input.value=value||'';input.addEventListener('click',function(ev){ev.stopPropagation();});input.addEventListener('input',function(){oninput(input.value);});return input;};
  RecognitionRulesPage.prototype.numberInput=function(value,min,max,step,oninput){var input=document.createElement('input');input.type='number';input.value=value;input.min=min;input.max=max;input.step=step;input.addEventListener('click',function(ev){ev.stopPropagation();});input.addEventListener('input',function(){var n=Number(input.value);if(isFinite(n))oninput(n);});return input;};
  RecognitionRulesPage.prototype.check=function(value,onchange){var input=document.createElement('input');input.type='checkbox';input.checked=!!value;input.addEventListener('click',function(ev){ev.stopPropagation();});input.addEventListener('change',function(){onchange(input.checked);});return input;};
  RecognitionRulesPage.prototype.modeSelect=function(value,onchange){var select=document.createElement('select');var current=value||'通配符';select.addEventListener('click',function(ev){ev.stopPropagation();});this.matchModes.forEach(function(mode){var option=document.createElement('option');option.value=mode;option.textContent=mode;if(mode===current)option.selected=true;select.appendChild(option);});select.addEventListener('change',function(){onchange(select.value);});return select;};
  RecognitionRulesPage.prototype.valueSelect=function(values,value,onchange){var select=document.createElement('select');var current=value||values[0];select.addEventListener('click',function(ev){ev.stopPropagation();});values.forEach(function(item){var option=document.createElement('option');option.value=item;option.textContent=item;if(item===current)option.selected=true;select.appendChild(option);});select.addEventListener('change',function(){onchange(select.value);});return select;};
  RecognitionRulesPage.prototype.bindRowDrag=function(row,index){var self=this,handle=row.querySelector('.rr-drag');if(handle){handle.draggable=true;handle.title='拖拽排序';handle.addEventListener('click',function(ev){ev.stopPropagation();});handle.addEventListener('dragstart',function(ev){self.dragIndex=index;row.classList.add('dragging');if(ev.dataTransfer)ev.dataTransfer.effectAllowed='move';});handle.addEventListener('dragend',function(){self.dragIndex=null;row.classList.remove('dragging','drag-target');});}row.addEventListener('dragover',function(ev){if(self.dragIndex==null||self.dragIndex===index)return;ev.preventDefault();row.classList.add('drag-target');});row.addEventListener('dragleave',function(){row.classList.remove('drag-target');});row.addEventListener('drop',function(ev){if(self.dragIndex==null||self.dragIndex===index)return;ev.preventDefault();var from=self.dragIndex,box=row.getBoundingClientRect(),to=index+(ev.clientY>box.top+box.height/2?1:0),item=self.rules.splice(from,1)[0];if(from<to)to--;to=Math.max(0,Math.min(self.rules.length,to));self.rules.splice(to,0,item);self.selectedIndex=to;self.dragIndex=null;self.render();});};
  RecognitionRulesPage.prototype.updateStatus=function(){
    var dirty=this.buildPayload()!==this.savedPayload, status=this.$('#rulesStatus');
    status.textContent=dirty?'未保存':'已保存';status.classList.toggle('dirty',dirty);
  };
  RecognitionRulesPage.prototype.renderList=function(){
    var body=this.$('#rulesBody'),self=this,q=this.$('#rulesSearch').value.trim().toLowerCase();
    body.innerHTML='';var indices=[];
    this.rules.forEach(function(rule,index){if(!q||self.ruleText(rule).indexOf(q)>=0)indices.push(index);});
    if(indices.indexOf(this.selectedIndex)<0)this.selectedIndex=indices.length?indices[0]:-1;
    indices.forEach(function(index){
      var rule=self.rules[index], row=document.createElement('div');row.className='rr-rule'+(index===self.selectedIndex?' selected':'')+(rule.enabled?'':' disabled');
      var drag=document.createElement('span');drag.className='rr-drag';drag.textContent='⋮⋮';drag.setAttribute('aria-hidden','true');row.appendChild(drag);
      var pick=document.createElement('button');pick.type='button';pick.className='rr-pick';pick.dataset.index=index;pick.setAttribute('aria-current',index===self.selectedIndex?'true':'false');
      var title=document.createElement('strong');title.textContent=(index+1)+'. '+(rule.name||'未命名规则');pick.appendChild(title);
      var sub=document.createElement('small');sub.textContent=(rule.enabled?'':'已停用 · ')+rule.matchMode+' · '+(rule.pattern||'待填写匹配内容');pick.appendChild(sub);pick.title=title.textContent+'\n'+sub.textContent;
      pick.onclick=function(){self.selectedIndex=index;self.render();var selected=self.$('.rr-rule.selected .rr-pick');if(selected)selected.focus();};
      row.appendChild(pick);self.bindRowDrag(row,index);body.appendChild(row);
    });
    this.$('#rulesCount').textContent=q?indices.length+' / '+this.rules.length+' 条规则':this.rules.length+' 条规则';
    this.$('#rulesEmpty').hidden=indices.length>0;this.$('#deleteRuleButton').disabled=this.selectedIndex<0;
  };
  RecognitionRulesPage.prototype.renderDetail=function(){
    var box=this.$('#ruleDetail'),self=this,rule=this.rules[this.selectedIndex];box.innerHTML='';
    if(!rule){box.innerHTML='<div class="rr-detail-empty">选择一条规则，或新增规则开始编辑。</div>';return;}
    var head=document.createElement('header');head.className='rr-detail-head';var title=document.createElement('h2');title.textContent=rule.name||'未命名规则';head.appendChild(title);
    var enabled=document.createElement('label');enabled.className='rr-check';enabled.appendChild(this.check(rule.enabled,function(v){rule.enabled=v;self.render();}));enabled.appendChild(document.createTextNode('启用规则'));head.appendChild(enabled);box.appendChild(head);
    function field(parent,label,key,options){
      options=options||{};var node=document.createElement('label');node.className='rr-field'+(options.wide?' wide':'');var caption=document.createElement('span');caption.textContent=label;node.appendChild(caption);
      function changed(v){rule[key]=v;self.updateStatus();var item=self.$('.rr-rule.selected .rr-pick');if(item){item.querySelector('strong').textContent=(self.selectedIndex+1)+'. '+(rule.name||'未命名规则');item.querySelector('small').textContent=(rule.enabled?'':'已停用 · ')+rule.matchMode+' · '+(rule.pattern||'待填写匹配内容');}title.textContent=rule.name||'未命名规则';}
      var input=options.values?self.valueSelect(options.values,rule[key],changed):options.number?self.numberInput(rule[key],options.min,options.max,options.step,changed):self.textInput(rule[key],changed);
      input.dataset.field=key;input.setAttribute('aria-label',label);if(options.placeholder)input.placeholder=options.placeholder;node.appendChild(input);
      if(options.hint){var hint=document.createElement('small');hint.textContent=options.hint;node.appendChild(hint);}parent.appendChild(node);
    }
    function section(name,hint){var section=document.createElement('section');section.className='rr-section';var h=document.createElement('h3');h.textContent=name;section.appendChild(h);if(hint){var p=document.createElement('p');p.className='rr-section-hint';p.textContent=hint;section.appendChild(p);}var fields=document.createElement('div');fields.className='rr-fields';section.appendChild(fields);box.appendChild(section);return fields;}
    var identity=document.createElement('div');identity.className='rr-fields';box.appendChild(identity);
    field(identity,'规则名称','name',{wide:true});
    var match=section('匹配条件');
    field(match,'匹配方式','matchMode',{values:this.matchModes});field(match,'匹配范围','scope');
    field(match,'匹配内容','pattern',{placeholder:'例如：*波纹管*'});field(match,'排除条件','excludePattern',{placeholder:'选填，多个关键词用逗号分隔'});
    var output=section('输出属性','命中规则后，按以下内容填写图层属性。');
    field(output,'父属性','parentGroup');field(output,'分类','parentClass');field(output,'标签','tagText',{wide:true,placeholder:'多个标签用逗号分隔'});
    var exec=section('执行方式','优先级越大越先执行；相同优先级按左侧列表顺序执行。');
    field(exec,'优先级','priority',{number:true,min:1,max:9999,step:1});field(exec,'合并方式','mergeMode',{values:this.mergeModes});
    var stop=document.createElement('label');stop.className='rr-check';stop.appendChild(this.check(rule.stopAfterMatch,function(v){rule.stopAfterMatch=v;self.updateStatus();}));stop.appendChild(document.createTextNode('命中后停止后续规则'));exec.appendChild(stop);
    var order=document.createElement('div');order.className='rr-order-tools';[-1,1].forEach(function(step){var btn=document.createElement('button');btn.textContent=step<0?'上移':'下移';btn.disabled=self.selectedIndex+step<0||self.selectedIndex+step>=self.rules.length;btn.onclick=function(){var to=self.selectedIndex+step;self.rules.splice(self.selectedIndex,1);self.rules.splice(to,0,rule);self.selectedIndex=to;self.render();};order.appendChild(btn);});exec.appendChild(order);
  };
  RecognitionRulesPage.prototype.render=function(){this.renderList();this.renderDetail();this.updateStatus();};
  RecognitionRulesPage.prototype.openSearch=function(){var input=this.$('#rulesSearch');input.focus();input.select();};
  RecognitionRulesPage.prototype.closeSearchIfEmpty=function(){};

  RecognitionRulesPage.prototype.addRule=function(){this.rules.push({id:'',name:'新规则',enabled:true,priority:100,scope:'图层名',matchMode:'通配符',pattern:'',excludePattern:'',parentGroup:'',parentClass:'',tagText:'',mergeMode:'覆盖空值',applicableObjectTypes:'',source:'用户规则',confidenceBase:.78,stopAfterMatch:true});this.selectedIndex=this.rules.length-1;this.$('#rulesSearch').value='';this.render();var input=this.$('[data-field=name]');if(input){input.focus();input.select();}};
  RecognitionRulesPage.prototype.deleteRule=function(){if(this.selectedIndex<0||this.selectedIndex>=this.rules.length)return;if(!confirm('删除当前选中的识别规则？'))return;this.rules.splice(this.selectedIndex,1);if(this.selectedIndex>=this.rules.length)this.selectedIndex=this.rules.length-1;this.render();};
  RecognitionRulesPage.prototype.restoreDefault=function(){if(!confirm('恢复默认属性识别表会覆盖当前页面中的编辑内容，保存前不会写入文件。是否继续？'))return;this.rules=cloneRules(this.defaultRules);this.selectedIndex=this.rules.length?0:-1;this.render();this.toast('已恢复为默认表，点击保存后生效','info');};
  RecognitionRulesPage.prototype.buildPayload=function(){return this.rules.map(function(r){return [r.enabled?'1':'0',String(Number(r.priority)||100),r.name||'',r.scope||'图层名',r.matchMode||'通配符',r.pattern||'',r.excludePattern||'',r.parentGroup||'',r.parentClass||'',r.tagText||'',r.mergeMode||'覆盖空值',r.applicableObjectTypes||'',r.source||'用户规则',String(Number(r.confidenceBase)||.78),r.stopAfterMatch?'1':'0'].map(b64).join('\t');}).join('\n');};
  RecognitionRulesPage.prototype.matches=function(rule,name){if(!rule.enabled||!rule.pattern)return false;var n=String(name||'').replace(/\s+/g,''),p=String(rule.pattern||'').replace(/\s+/g,''),ex=String(rule.excludePattern||'').split(/[，,、;；|]/).filter(Boolean);if(ex.some(function(x){return n.toLowerCase().indexOf(x.trim().toLowerCase())>=0;}))return false;try{if(rule.matchMode==='精确')return n.toLowerCase()===p.toLowerCase();if(rule.matchMode==='包含')return n.toLowerCase().indexOf(p.toLowerCase())>=0;if(rule.matchMode==='正则')return new RegExp(rule.pattern,'i').test(name);if(rule.matchMode==='关键词组合')return p.split(/[，,、;；|]/).filter(Boolean).every(function(x){return n.toLowerCase().indexOf(x.trim().toLowerCase())>=0;});var rx='^'+p.replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*').replace(/\?/g,'.')+'$';if(rule.matchMode==='模板')rx='^'+p.replace(/[.+^$()|[\]\\]/g,'\\$&').replace(/\\?\{DN\}/g,'(?:DN)?\\d+(?:\\.\\d+)?').replace(/\\?\{D\}/g,'D\\d+(?:\\.\\d+)?').replace(/\\?\{T\}/g,'T\\d+(?:\\.\\d+)?').replace(/\\?\{(?:Material|Type)\}/g,'.+?').replace(/\*/g,'.*')+'$';return new RegExp(rx,'i').test(n);}catch(ex2){return false;}};
  RecognitionRulesPage.prototype.testRules=function(){var input=this.$('#ruleTestInput'),output=this.$('#ruleTestOutput');if(!input||!output)return;var self=this,names=(input.value||'').split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);if(!names.length){output.textContent='请先输入至少一个图层名。';return;}var ordered=this.rules.map(function(r,i){return {r:r,i:i};}).sort(function(a,b){return (Number(b.r.priority)||0)-(Number(a.r.priority)||0)||a.i-b.i;});output.textContent=names.map(function(name){var hits=ordered.filter(function(x){return self.matches(x.r,name);}).map(function(x){var r=x.r;return (r.name||('#'+(x.i+1)))+' → '+[r.parentGroup,r.parentClass,r.tagText].filter(Boolean).join(' / ');});return name+'\n  '+(hits.length?hits.join('\n  '):'未命中规则（仍会由名称提取器分析）');}).join('\n\n');};
  RecognitionRulesPage.prototype.bind=function(){if(this.bound)return;this.bound=true;var self=this;var bind=function(selector,event,handler){var node=self.$(selector);if(node)node.addEventListener(event,handler);};bind('#toggleSearch','click',function(){var wrap=self.$('#searchWrap');var input=self.$('#rulesSearch');if(!wrap||!input)return;if(wrap.classList.contains('open')){if(input.value){input.value='';self.render();}wrap.classList.remove('open');}else self.openSearch();});bind('#rulesSearch','input',function(){self.render();});bind('#rulesSearch','blur',function(){self.closeSearchIfEmpty();});bind('#addRuleButton','click',function(){self.addRule();});bind('#deleteRuleButton','click',function(){self.deleteRule();});bind('#testRulesButton','click',function(){self.testRules();});bind('#restoreDefaultRulesButton','click',function(){self.restoreDefault();});bind('#saveRulesButton','click',function(){var invalid=self.root.querySelector('input:invalid');if(invalid){invalid.reportValidity();return;}self.post('saveRecognitionRules',self.buildPayload());});bind('#openLegacyRecognition','click',function(){self.post('openLegacyRecognition','');});bind('#closeWindow','click',function(){self.post('close','');});document.addEventListener('keydown',function(ev){var visible=self.root.offsetParent!==null||self.options.standalone;if(!visible)return;if((ev.ctrlKey||ev.metaKey)&&String(ev.key).toLowerCase()==='f'){ev.preventDefault();self.openSearch();}else if((ev.ctrlKey||ev.metaKey)&&String(ev.key).toLowerCase()==='s'){ev.preventDefault();self.$('#saveRulesButton').click();}else if(ev.key==='Escape'){self.closeSearchIfEmpty();}});};
  RecognitionRulesPage.prototype.init=function(){this.bind();this.render();return this;};
  w.CDBoxRecognitionRulesPage={create:function(options){return new RecognitionRulesPage(options).init();},cloneRules:cloneRules};
})(window);
