using System.Text;
using TCPipeAutoDraw.Core.Startup;

namespace TCPipeAutoDraw.UI.Studio
{
    internal static class CDBoxStudioSettingsPage
    {
        public static string BuildStandaloneDocument()
        {
            CDBoxStudioSettings settings = CDBoxStudioSettingsStore.Load();
            CDBoxAppSettings app = CDBoxAppSettingsStore.Load();
            var html = new StringBuilder();
            html.Append("<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>CDBox设置</title><style>");
            html.Append(@":root{--bg:#f5f7fb;--panel:#fff;--panel2:#f8fafc;--text:#162033;--muted:#64748b;--line:#dce5f1;--brand:#326fea;--brand2:#7c3aed;--ok:#059669;--warn:#d97706;--err:#dc2626}body[data-theme='fresh']{--bg:#f2f6ff;--panel2:#edf4ff;--line:#d7e5ff}body[data-theme='dark']{--bg:#0f172a;--panel:#172033;--panel2:#111827;--text:#e5e7eb;--muted:#94a3b8;--line:#2b3a50;--brand:#60a5fa;--brand2:#a78bfa}*{box-sizing:border-box}html,body{height:100%;margin:0;background:var(--bg);color:var(--text);font-family:'Microsoft YaHei UI','Segoe UI',sans-serif}body{overflow:auto;padding:12px 22px 28px}.page{max-width:1180px;margin:auto}.head,.card{background:var(--panel);border:1px solid var(--line);border-radius:20px;box-shadow:0 12px 28px rgba(30,41,59,.07)}.head{padding:22px 24px;margin-bottom:14px}.head h1{margin:0;font-size:24px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{padding:18px}.wide{grid-column:1/-1}.card h2{margin:0 0 14px;font-size:17px}.themes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.theme{border:1px solid var(--line);background:var(--panel2);border-radius:14px;padding:13px;cursor:pointer}.theme:has(input:checked){border-color:var(--brand);box-shadow:0 0 0 3px rgba(50,111,234,.1)}.switch{display:flex;align-items:center;gap:10px}.switch input{width:18px;height:18px;accent-color:var(--brand)}.paths{display:grid;grid-template-columns:1fr 1fr;gap:10px}.paths label{font-size:12px;color:var(--muted)}code{display:block;margin-top:5px;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--panel2);color:var(--text);word-break:break-all}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}button,input,select{font:inherit}button{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:11px;padding:9px 13px;font-weight:700;cursor:pointer}.primary{border:0;color:#fff;background:linear-gradient(135deg,var(--brand),var(--brand2))}.danger{color:#b91c1c;border-color:#fecaca}.update-row{display:grid;grid-template-columns:170px minmax(280px,1fr) auto;gap:10px;align-items:end}.field{display:grid;gap:6px;color:var(--muted);font-size:12px}.field input,.field select{height:40px;border:1px solid var(--line);border-radius:10px;background:var(--panel2);color:var(--text);padding:0 10px}.progress{display:none;margin-top:12px;color:var(--muted)}.progress.show{display:block}.result{margin-top:12px;padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel2);white-space:pre-wrap;word-break:break-word}.toast{position:fixed;right:22px;top:58px;max-width:420px;padding:12px 15px;border-radius:12px;background:var(--panel);border:1px solid var(--line);box-shadow:0 16px 38px rgba(15,23,42,.18);z-index:10}.no-animations *{animation:none!important;transition:none!important}@media(max-width:900px){.grid,.themes,.paths,.update-row{grid-template-columns:1fr}} ");
            html.Append("</style></head><body data-theme=\"").Append(A(settings.Theme)).Append("\" class=\"").Append(settings.AnimationsEnabled ? string.Empty : "no-animations").Append("\"><main class=\"page\"><header class=\"head\"><h1>CDBox设置</h1></header><div class=\"grid\">");
            html.Append("<section class=\"card wide\"><h2>界面</h2><div class=\"themes\">");
            Theme(html, "light", "明亮浅色", settings.Theme); Theme(html, "fresh", "蓝紫现代", settings.Theme); Theme(html, "dark", "深色护眼", settings.Theme);
            html.Append("</div><div class=\"actions\"><label class=\"switch\"><input id=\"animations\" type=\"checkbox\"").Append(settings.AnimationsEnabled ? " checked" : string.Empty).Append(">启用界面动画</label></div></section>");
            html.Append("<section class=\"card\"><h2>启动设置</h2><label class=\"switch\"><input id=\"promptInstall\" type=\"checkbox\"").Append(app.PromptInstallOnLoad ? " checked" : string.Empty).Append(">未安装时提示安装自动加载</label></section>");
            html.Append("<section class=\"card\"><h2>安装状态</h2><strong>").Append(CDBoxInstaller.IsInstalled() ? "已安装" : "未安装").Append("</strong></section>");
            html.Append("<section class=\"card wide\"><h2>安装与本地更新</h2><div class=\"paths\"><label>CAD 目录<code>").Append(H(CDBoxInstaller.GetCadDirectory())).Append("</code></label><label>安装目录<code>").Append(H(CDBoxInstaller.GetInstallRoot())).Append("</code></label></div><div class=\"actions\"><button class=\"primary\" data-route=\"installPlugin\">安装/修复自动加载</button><button data-route=\"localUpdatePlugin\">本地更新</button><button class=\"danger\" data-route=\"uninstallPlugin\">卸载自动加载</button><button data-route=\"openLogs\">打开日志目录</button></div></section>");
            html.Append("<section class=\"card wide\"><h2>网络更新</h2><div class=\"update-row\"><label class=\"field\">更新通道<select id=\"channel\"><option value=\"studio-preview\">studio-preview</option></select></label><label class=\"field\">update.json 更新源<input id=\"source\" value=\"").Append(A(settings.UpdateSourceUrl)).Append("\"></label><div class=\"actions\"><button class=\"primary\" id=\"check\">检查更新</button><button id=\"download\" disabled>下载并准备安装</button></div></div><div id=\"progress\" class=\"progress\"></div><div id=\"result\" class=\"result\">尚未检查更新</div></section>");
            html.Append("</div></main><script>");
            html.Append(@"(function(){var latest=null;function post(n,a){if(window.chrome&&chrome.webview)chrome.webview.postMessage('studio|'+n+'|'+encodeURIComponent(a||''));}function payload(){var t=(document.querySelector('input[name=theme]:checked')||{}).value||'light';return 'theme='+encodeURIComponent(t)+'&animations='+(document.getElementById('animations').checked?'1':'0')+'&promptInstall='+(document.getElementById('promptInstall').checked?'1':'0')+'&updateChannel='+encodeURIComponent(document.getElementById('channel').value)+'&updateSourceUrl='+encodeURIComponent(document.getElementById('source').value||'');}function save(){var t=(document.querySelector('input[name=theme]:checked')||{}).value||'light';document.body.dataset.theme=t;document.body.classList.toggle('no-animations',!document.getElementById('animations').checked);post('settings',payload());}document.querySelectorAll('input[name=theme],#animations,#promptInstall').forEach(function(x){x.addEventListener('change',save);});document.querySelectorAll('[data-route]').forEach(function(x){x.addEventListener('click',function(){post(x.dataset.route,'');});});document.getElementById('check').onclick=function(){latest=null;document.getElementById('download').disabled=true;document.getElementById('progress').className='progress show';document.getElementById('progress').textContent='正在检查更新';post('checkUpdate',payload());};document.getElementById('download').onclick=function(){post('downloadUpdate',payload());};window.CDBoxStudioUpdateProgress=function(d){document.getElementById('progress').className='progress show';document.getElementById('progress').textContent=(d.message||'正在处理')+(d.percent?' · '+d.percent+'%':'');};window.CDBoxStudioUpdateResult=function(d){latest=d;document.getElementById('progress').className='progress';document.getElementById('result').textContent=d.success?(d.updateAvailable?'发现新版本：'+d.latestVersion:'当前已是最新版本'):('检查失败：'+(d.errorMessage||'未知错误'));document.getElementById('download').disabled=!(d.success&&d.updateAvailable);};window.CDBoxStudioDownloadResult=function(d){document.getElementById('progress').className='progress';document.getElementById('result').textContent=d.success&&d.verified?'更新包已校验，请关闭 CAD 完成更新':'更新准备失败：'+(d.errorMessage||d.installerErrorMessage||'未知错误');};window.CDBoxStudioToast=function(m,k){var x=document.createElement('div');x.className='toast';x.textContent=m||'';document.body.appendChild(x);setTimeout(function(){x.remove();},2800);};setTimeout(function(){post('ready','settings');},50);})();");
            html.Append("</script></body></html>");
            return html.ToString();
        }

        private static void Theme(StringBuilder html, string value, string title, string current)
        {
            html.Append("<label class=\"theme\"><input type=\"radio\" name=\"theme\" value=\"").Append(value).Append("\"");
            if (string.Equals(value, current, System.StringComparison.OrdinalIgnoreCase)) html.Append(" checked");
            html.Append(">").Append(title).Append("</label>");
        }

        private static string H(string value) { return A(value); }
        private static string A(string value) { return (value ?? string.Empty).Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;"); }
    }
}
